name: deployment-to-gh-pages

on:
  push:
    branches:
      - ng/master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout ğŸ›ï¸
      uses: actions/checkout@v3
    - name: Set up node.js ğŸ”§
      uses: actions/setup-node@v3
      with:
        node-version: 16.15.1
        cache: 'npm'
    - name: Install angular-cli ğŸ”§
      run: npm install -g @angular/cli > /dev/null
    - name: Build angular application ğŸ”§
      run: ng build --prod --output-path=dist 
    - name: Deploy to gh-pages ğŸš€
      if: github.event_name != 'pull_request'
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: dist